name: Tests

on:
  pull_request:
    paths:
      - "auth-service/**"
  push:
    paths:
      - "auth-service/**"

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: auth-service

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: yarn
          cache-dependency-path: ${{ github.workspace }}/auth-service/yarn.lock

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run Vitest
        run: yarn vitest run
